version: '3.7'
services:
  workspace:
    build:
      context: ./docker/go
    environment:
      - APP_ENV=production
    volumes:
      - ./:/go/app
  db:
    build:
      context: ./docker/mysql
    container_name: news_db
    volumes:
      - ./db_data:/var/lib/mysql:cached
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

