version: '3.7'
services:
  db:
    build:
      context: .
    container_name: news_db
    volumes:
      - db_data:/var/lib/mysql:cached
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: news_password

volumes:
  db_data:
